//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.MyDslModeling
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "MyDslModeling";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"MyDslModeling";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID MyDslModelingDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MyDslModelingCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID MyDslModelingExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MyDslModelingCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewMyDslModelingExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MyDslModelingCommandSetId), 0x0001);
	
		// Package identifier
		public const string MyDslModelingPackageId = "386f7c38-014e-428b-90a8-c1a245a5361e";
		
		// Editor factory identifier
		public const string MyDslModelingEditorFactoryId = "b907fe2d-963e-4749-a172-9c20826694c7";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string MyDslModelingModelExplorerToolWindowId = "4edd8f50-0935-4ebc-bc7b-6b342dcbee98";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.MyDslModeling
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string MyDslModelingCommandSetId = "69b86e9c-470a-44b1-a473-719af5a55ecb";
	}
}