//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.MyDslXYCoordinates
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "MyDslXYCoordinates";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"MyDslXYCoordinates";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID MyDslXYCoordinatesDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MyDslXYCoordinatesCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID MyDslXYCoordinatesExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MyDslXYCoordinatesCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewMyDslXYCoordinatesExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MyDslXYCoordinatesCommandSetId), 0x0001);
	
		// Package identifier
		public const string MyDslXYCoordinatesPackageId = "423c4d6f-fa08-4062-83a2-76b3bb8bc0db";
		
		// Editor factory identifier
		public const string MyDslXYCoordinatesEditorFactoryId = "91e13b8e-fa11-49a5-84ad-f62c9905e47e";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string MyDslXYCoordinatesModelExplorerToolWindowId = "b4c18f42-bb7d-4cc3-924b-106b9cb6e42b";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.MyDslXYCoordinates
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string MyDslXYCoordinatesCommandSetId = "009f5b28-7e6d-4758-83a0-17d383a338dd";
	}
}