//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.MyDslComponents
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "MyDslComponents";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"MyDslComponents";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID MyDslComponentsDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MyDslComponentsCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID MyDslComponentsExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MyDslComponentsCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewMyDslComponentsExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MyDslComponentsCommandSetId), 0x0001);
	
		// Package identifier
		public const string MyDslComponentsPackageId = "8bf03763-7a37-44f3-8516-11ef3578ac6f";
		
		// Editor factory identifier
		public const string MyDslComponentsEditorFactoryId = "76753c16-6eca-44c9-a1dc-72ec21a12449";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string MyDslComponentsModelExplorerToolWindowId = "01cc0083-dd8e-4398-994b-1596a875d49b";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.MyDslComponents
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string MyDslComponentsCommandSetId = "843bcce9-48bf-46fe-a943-252beef01919";
	}
}