//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.MyDSL
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "MyDSL";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"MyDSL";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID MyDSLDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MyDSLCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID MyDSLExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MyDSLCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewMyDSLExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MyDSLCommandSetId), 0x0001);
	
		// Package identifier
		public const string MyDSLPackageId = "712081f4-a117-40ea-9c8e-9517f6e78c6d";
		
		// Editor factory identifier
		public const string MyDSLEditorFactoryId = "32f644ae-4625-44f6-acac-6f85502bfe71";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string MyDSLModelExplorerToolWindowId = "6ff6bd9d-20ca-42e9-833c-399dbd5521e4";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.MyDSL
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string MyDSLCommandSetId = "55bd2622-238f-43ad-bcd5-db5ad0a27230";
	}
}