//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.MyDslCompartment
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "MyDslCompartment";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"MyDslCompartment";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID MyDslCompartmentDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MyDslCompartmentCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID MyDslCompartmentExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MyDslCompartmentCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewMyDslCompartmentExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MyDslCompartmentCommandSetId), 0x0001);
	
		// Package identifier
		public const string MyDslCompartmentPackageId = "9ee42bd8-bdc7-4f23-b186-abb0bea36a69";
		
		// Editor factory identifier
		public const string MyDslCompartmentEditorFactoryId = "e1a012a1-08da-49dd-bbbe-6c56454128be";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string MyDslCompartmentModelExplorerToolWindowId = "6e8212c7-4f53-414e-9a57-a0afcc898438";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.MyDslCompartment
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string MyDslCompartmentCommandSetId = "fab481fd-186d-4e50-ace2-558d6de11ed1";
	}
}