//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.MyDslPorts
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "MyDslPorts";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"MyDslPorts";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID MyDslPortsDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MyDslPortsCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID MyDslPortsExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MyDslPortsCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewMyDslPortsExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MyDslPortsCommandSetId), 0x0001);
	
		// Package identifier
		public const string MyDslPortsPackageId = "82abe8f5-e749-4235-80e6-de8c2202eec2";
		
		// Editor factory identifier
		public const string MyDslPortsEditorFactoryId = "e1ba2f50-9bce-4f79-bf5f-8d4077ab6e4b";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string MyDslPortsModelExplorerToolWindowId = "d76344e0-77b5-4fd0-8375-36f35c2242b0";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.MyDslPorts
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string MyDslPortsCommandSetId = "fa463272-638b-4033-a1a0-64e657d954e4";
	}
}